name: api Tests
on:
  workflow_dispatch:
  push:
    branches: [main, master]
  # pull_request:
  #   branches: [main, master]
jobs:
  api_test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci

      - name: Install allure-commandline
        run: npm install allure-commandline

      - name: Run Playwright tests
        run: npx playwright test
        env:
          CI: true
          USER_NAME: ${{ secrets.USER_NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SITE_ID: ${{ secrets.SITE_ID }}
      - name: Save Screenshots
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: "Test report"
          state: "success"
          sha: ${{ github.event.pull_request.head.sha }}
          target_url: https://chooton838.github.io/github-allure-history/${{ github.run_number }}

    # - name: Generate Allure Report
    #   run: allure generate allure-results -o allure-report --clean

    # - uses: actions/upload-artifact@master
    #   with:
    #     name: allure-results
    #     path: allure-results
    #     retention-days: 20

    # - name: Get Allure history
    #   uses: actions/checkout@v2
    #   if: always()
    #   continue-on-error: true
    #   with:
    #     ref: gh-pages
    #     path: gh-pages

    # - name: Test marketplace action
    #   uses: simple-elf/allure-report-action@master
    #   if: always()
    #   id: allure-report
    #   with:
    #     allure_results: allure-results
    #     gh_pages: gh-pages
    #     allure_report: allure-report
    #     allure_history: allure-history
    #     keep_reports: 20

    # - name: Deploy report to Github Pages
    #   if: always()
    #   uses: peaceiris/actions-gh-pages@v2
    #   env:
    #     PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
    #     PUBLISH_BRANCH: gh-pages
    #     PUBLISH_DIR: allure-history
